// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopEntertainment.Juegos.AccessData;

#nullable disable

namespace TopEntertainment.Juegos.AccessData.Migrations
{
    [DbContext(typeof(JuegosContext))]
    [Migration("20220707153430_Juegos")]
    partial class Juegos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descripcion = "https://e7.pngegg.com/pngimages/136/884/png-clipart-clear-vision-3-sniper-shooter-clear-vision-2-sniper-fury-sniper-3d-gun-shooter-free-bullet-shooting-games-sniper-lens-android-sniper-fury.png",
                            NombreCategoria = "Accion"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descripcion = "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/styles/hc_1440x810/public/media/image/2017/12/mejores-juegos-accion-aventura-2018.jpg?itok=8GmFr_E5",
                            NombreCategoria = "Aventura"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descripcion = "https://thumbs.dreamstime.com/b/icono-de-reglas-juego-elemento-simple-la-colecci%C3%B3n-desarrollo-juegos-rellenas-para-plantillas-infograf%C3%ADas-y-m%C3%A1s-signo-creativo-193118532.jpg",
                            NombreCategoria = "Estrategia"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Descripcion = "https://alfabetajuega.com/hero/2021/04/battlefield-bad-company-2.jpg?width=1200&aspect_ratio=1200:631",
                            NombreCategoria = "Disparos"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Descripcion = "https://img.captain-droid.com/wp-content/uploads/2017/11/eyes-icon.png",
                            NombreCategoria = "Terror"
                        },
                        new
                        {
                            CategoriaId = 6,
                            Descripcion = "https://is2-ssl.mzstatic.com/image/thumb/Purple62/v4/ba/ab/f5/baabf5f7-0bc7-5ae1-9de3-85a71b389617/mzl.yixomytg.png/230x0w.png",
                            NombreCategoria = "Casual"
                        },
                        new
                        {
                            CategoriaId = 7,
                            Descripcion = "https://img.freepik.com/vector-gratis/pad-juego-moderno-alambre-videojuegos-joystick-3d-azul-videoconsola-fondo-simbolos-geometricos-dinamicos-concepto-juegos-computadora-diseno-su-plantilla-ilustracion-vectorial_185386-790.jpg?w=360",
                            NombreCategoria = "Plataforma"
                        },
                        new
                        {
                            CategoriaId = 8,
                            Descripcion = "https://www.androidsis.com/wp-content/uploads/2018/02/Juegos-de-supervivencia.png",
                            NombreCategoria = "Supervivencia"
                        },
                        new
                        {
                            CategoriaId = 9,
                            Descripcion = "https://w7.pngwing.com/pngs/118/906/png-transparent-video-game-platform-game-5-miscellaneous-game-video-game-thumbnail.png",
                            NombreCategoria = "Mundo Abierto"
                        },
                        new
                        {
                            CategoriaId = 10,
                            Descripcion = "https://as01.epimg.net/meristation/imagenes/2018/09/15/reportajes/1537047527_669497_1537047584_sumario_normal.jpg",
                            NombreCategoria = "Primera Persona"
                        },
                        new
                        {
                            CategoriaId = 11,
                            Descripcion = "https://c8.alamy.com/compes/2cb364b/icono-juego-de-simulacion-elemento-simple-de-la-coleccion-de-desarrollo-de-juegos-icono-de-juego-de-simulacion-relleno-para-plantillas-infografias-y-mucho-mas-2cb364b.jpg",
                            NombreCategoria = "Simulacion"
                        },
                        new
                        {
                            CategoriaId = 12,
                            Descripcion = "https://static.vecteezy.com/system/resources/previews/004/976/735/non_2x/gaming-accessory-glyph-icon-pc-steering-wheel-esports-device-gadget-for-driving-simulation-game-racing-silhouette-symbol-negative-space-isolated-illustration-vector.jpg",
                            NombreCategoria = "Carrera"
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Clasificacion", b =>
                {
                    b.Property<int>("ClasificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClasificacionId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombreClasificacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ClasificacionId");

                    b.ToTable("Clasificacion", (string)null);

                    b.HasData(
                        new
                        {
                            ClasificacionId = 1,
                            Descripcion = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/ESRB_2013_Everyone_Spanish.svg/800px-ESRB_2013_Everyone_Spanish.svg.png",
                            NombreClasificacion = "E for Everyone."
                        },
                        new
                        {
                            ClasificacionId = 2,
                            Descripcion = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/ESRB_2013_Teen_Spanish.svg/800px-ESRB_2013_Teen_Spanish.svg.png",
                            NombreClasificacion = "PG 16"
                        },
                        new
                        {
                            ClasificacionId = 3,
                            Descripcion = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/ESRB_2013_Adults_Only_Spanish.svg/800px-ESRB_2013_Adults_Only_Spanish.svg.png",
                            NombreClasificacion = "PG 18"
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Imagen", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenId"), 1L, 1);

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.HasKey("ImagenId");

                    b.HasIndex("JuegoId");

                    b.ToTable("Imagenes");

                    b.HasData(
                        new
                        {
                            ImagenId = 1,
                            ImagenUrl = "https://i.imgur.com/4Hk05rT.png",
                            JuegoId = 1
                        },
                        new
                        {
                            ImagenId = 2,
                            ImagenUrl = "https://i.imgur.com/86iraFT.png",
                            JuegoId = 2
                        },
                        new
                        {
                            ImagenId = 3,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-godofwar-santamonicastudio-g1a-02-1920x1080-f7c6fef5c876.jpg?h=720&resize=1&w=1280",
                            JuegoId = 3
                        },
                        new
                        {
                            ImagenId = 4,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-godofwar-santamonicastudio-g1a-01-1920x1080-c84d2a96aea3.jpg",
                            JuegoId = 3
                        },
                        new
                        {
                            ImagenId = 5,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-godofwar-santamonicastudio-g1a-03-1920x1080-65b80475ae32.jpg?h=720&resize=1&w=1280",
                            JuegoId = 3
                        },
                        new
                        {
                            ImagenId = 6,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/93ea0d593cb04e62afb0741bbf894173/EGS_RedoutEnhancedEdition_34BigThingssrl_S1_2560x1440-23ab955c6537efdd53e1f407609f9036?h=270&resize=1&w=480",
                            JuegoId = 4
                        },
                        new
                        {
                            ImagenId = 7,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-redoutenhancededition-34bigthingssrl-g1a-01-1920x1080-6e1e9ea24bd5.jpg",
                            JuegoId = 4
                        },
                        new
                        {
                            ImagenId = 8,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-redoutenhancededition-34bigthingssrl-g1a-02-1920x1080-8eb05ed7cc60.jpg",
                            JuegoId = 4
                        },
                        new
                        {
                            ImagenId = 9,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-redoutenhancededition-34bigthingssrl-g1a-03-1920x1080-b48ac6857dfe.jpg",
                            JuegoId = 4
                        },
                        new
                        {
                            ImagenId = 10,
                            ImagenUrl = "https://cdn2.unrealengine.com/es-es-fallguysss1-productofferabout-1920x1080-1920x1080-a204121647bc.jpg",
                            JuegoId = 5
                        },
                        new
                        {
                            ImagenId = 11,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-fallguys-mediatonic-g1a-01-1920x1080-063acacc6f1a.jpg",
                            JuegoId = 5
                        },
                        new
                        {
                            ImagenId = 12,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-fallguys-mediatonic-g1a-02-1920x1080-a5f24303b646.jpg",
                            JuegoId = 5
                        },
                        new
                        {
                            ImagenId = 13,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/9c59efaabb6a48f19b3485d5d9416032/EGS_LEGOStarWarsTheSkywalkerSaga_TTGames_S1_2560x1440-ae89e9c91aec1e461148f93f25b828ed?h=270&resize=1&w=480",
                            JuegoId = 6
                        },
                        new
                        {
                            ImagenId = 14,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-legostarwarstheskywalkersaga-ttgames-g1a-00-1920x1080-487a6e965579.jpg",
                            JuegoId = 6
                        },
                        new
                        {
                            ImagenId = 15,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-legostarwarstheskywalkersaga-ttgames-g1a-01-1920x1080-5da07b4a7838.jpg",
                            JuegoId = 6
                        },
                        new
                        {
                            ImagenId = 16,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-legostarwarstheskywalkersaga-ttgames-g1a-02-1920x1080-38aa896e6f5f.jpg",
                            JuegoId = 6
                        },
                        new
                        {
                            ImagenId = 17,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/Daffodil_1P_Awareness_INT_Epic_2560x1440_2560x1440-ba126bdeac3faab0596b7c56e9c09990?h=270&resize=1&w=480",
                            JuegoId = 7
                        },
                        new
                        {
                            ImagenId = 18,
                            ImagenUrl = "https://cdn2.unrealengine.com/ttwl-gameplay-reveal-screenshots-banshee-1080-1mb-1920x1080-bf235e1791e1.jpg",
                            JuegoId = 7
                        },
                        new
                        {
                            ImagenId = 19,
                            ImagenUrl = "https://cdn2.unrealengine.com/ttwl-gameplay-reveal-screenshots-mushroom-forest-1080-1mb-1920x1080-9f8ebad39534.jpg",
                            JuegoId = 7
                        },
                        new
                        {
                            ImagenId = 20,
                            ImagenUrl = "https://cdn2.unrealengine.com/crypt-01-3840x2160-4fd5e57cdc50.jpg",
                            JuegoId = 7
                        },
                        new
                        {
                            ImagenId = 21,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_TetrisEffectConnected_MonstarsincandResonair_S3_2560x1440-f2b7de145181b857418618f0ea6c4ad5?h=270&resize=1&w=480",
                            JuegoId = 8
                        },
                        new
                        {
                            ImagenId = 22,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tetriseffectconnected-monstarsincresonairstagegames-g1a-01-12-13-21-1920x1080-87cd4694250f.jpg",
                            JuegoId = 8
                        },
                        new
                        {
                            ImagenId = 23,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tetriseffectconnected-monstarsincresonairstagegames-g1a-02-12-13-21-1920x1080-346ccc7c35b6.jpg",
                            JuegoId = 8
                        },
                        new
                        {
                            ImagenId = 24,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tetriseffectconnected-monstarsincresonairstagegames-g1a-03-12-13-21-1920x1080-726caf36858c.jpg",
                            JuegoId = 8
                        },
                        new
                        {
                            ImagenId = 25,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/226306adde104c9092247dcd4bfa1499/EGS_CarMechanicSimulator2018_RedDotGames_S1_2560x1440-3489ef1499e64c168fdf4b14926d2c23?h=270&resize=1&w=480",
                            JuegoId = 9
                        },
                        new
                        {
                            ImagenId = 26,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-carmechanicsimulator2018-reddotgames-g1a-00-1920x1080-396668eaeb30.jpg",
                            JuegoId = 9
                        },
                        new
                        {
                            ImagenId = 27,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-carmechanicsimulator2018-reddotgames-g1a-02-1920x1080-c8d7441e80cd.jpg",
                            JuegoId = 9
                        },
                        new
                        {
                            ImagenId = 28,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-carmechanicsimulator2018-reddotgames-g1a-03-1920x1080-bfbe97557dc0.jpg",
                            JuegoId = 9
                        },
                        new
                        {
                            ImagenId = 29,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/5a52c72d-80fc-4c3f-bc24-52b09ab9896a_2560x1440-12a1d9b80efd050055faa72feee71f8e?h=270&resize=1&w=480",
                            JuegoId = 10
                        },
                        new
                        {
                            ImagenId = 30,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-valorant-riotgames-g1a-02-1920x1080-580683fffe0f.jpg",
                            JuegoId = 10
                        },
                        new
                        {
                            ImagenId = 31,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-valorant-riotgames-g1a-03-1920x1080-f34bc7b4f1b5.jpg",
                            JuegoId = 10
                        },
                        new
                        {
                            ImagenId = 32,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-valorant-riotgames-g1a-05-1920x1080-42cf018303e5.jpg",
                            JuegoId = 10
                        },
                        new
                        {
                            ImagenId = 33,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/0c6aee83b9b64372bf44a043001325f2/EGS_NARAKABLADEPOINT_24Entertainment_S1_2560x1440-62753d62ba83fc734916b63e3774cc4c?h=270&resize=1&w=480",
                            JuegoId = 11
                        },
                        new
                        {
                            ImagenId = 34,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-narakabladepoint-24entertainment-g1a-08-1920x1080-f1f3eade2832.jpg",
                            JuegoId = 11
                        },
                        new
                        {
                            ImagenId = 35,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-narakabladepoint-24entertainment-g1a-09-1920x1080-7d3aad3867aa.jpg",
                            JuegoId = 11
                        },
                        new
                        {
                            ImagenId = 36,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-narakabladepoint-24entertainment-g1a-10-1920x1080-e61c5693cd25.jpg",
                            JuegoId = 11
                        },
                        new
                        {
                            ImagenId = 37,
                            ImagenUrl = "https://cdn2.unrealengine.com/roll-02-3playersposing920x1080-1920x1080-8440693fc396.jpg",
                            JuegoId = 12
                        },
                        new
                        {
                            ImagenId = 38,
                            ImagenUrl = "https://cdn2.unrealengine.com/roll-03-superstaroption2-1920x1080-1920x1080-c6163a0beb18.jpg",
                            JuegoId = 12
                        },
                        new
                        {
                            ImagenId = 39,
                            ImagenUrl = "https://cdn2.unrealengine.com/roll-05-0-selectedairshot-1920x1080-1920x1080-43a1975d56ca.jpg",
                            JuegoId = 12
                        },
                        new
                        {
                            ImagenId = 40,
                            ImagenUrl = "https://cdn1.epicgames.com/b156c3365a5b4cb9a01a5e1108b4e3f4/offer/EGS_STARWARSBattlefrontIICelebrationEdition_DICE_S1-2560x1440-3dc68a07cace02e826ad42a2de5279b0.jpg?h=270&resize=1&w=480",
                            JuegoId = 13
                        },
                        new
                        {
                            ImagenId = 41,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-starwarsbattlefrontiicelebrationedition-dice-g1a-02-1920x1080-aeb9deb222c1.jpg",
                            JuegoId = 13
                        },
                        new
                        {
                            ImagenId = 42,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-starwarsbattlefrontiicelebrationedition-dice-g1a-03-1920x1080-9e43a5cc414f.jpg",
                            JuegoId = 13
                        },
                        new
                        {
                            ImagenId = 43,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-starwarsbattlefrontiicelebrationedition-dice-g1a-04-1920x1080-6ec1f5203cde.jpg",
                            JuegoId = 13
                        },
                        new
                        {
                            ImagenId = 44,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_WolfensteinTheNewOrder_MachineGames_S1_2560x1440-3a75b2c45a2a12e882feb2e2ff180b0c?h=270&resize=1&w=480",
                            JuegoId = 14
                        },
                        new
                        {
                            ImagenId = 45,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-wolfensteintheneworder-machinegames-g1a-07-1920x1080-75e96831363a.jpg",
                            JuegoId = 14
                        },
                        new
                        {
                            ImagenId = 46,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-wolfensteintheneworder-machinegames-g1a-08-1920x1080-ed79f030c810.jpg",
                            JuegoId = 14
                        },
                        new
                        {
                            ImagenId = 47,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-wolfensteintheneworder-machinegames-g1a-10-1920x1080-b73d1b85dc41.jpg",
                            JuegoId = 14
                        },
                        new
                        {
                            ImagenId = 48,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_HoodOutlawsLegends_SumoDigital_S1_2560x1440-8ba1f9be04e3d0c07f9890a0bb8860c7?h=270&resize=1&w=480",
                            JuegoId = 15
                        },
                        new
                        {
                            ImagenId = 49,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hoodoutlawslgends-sumodigital-g1a-03-1920x1080-b28210417461.jpg",
                            JuegoId = 15
                        },
                        new
                        {
                            ImagenId = 50,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hoodoutlawslgends-sumodigital-g1a-05-1920x1080-6b0b8e9f52f2.jpg",
                            JuegoId = 15
                        },
                        new
                        {
                            ImagenId = 51,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hoodoutlawslgends-sumodigital-g1a-06-1920x1080-d9c895eaeff0.jpg",
                            JuegoId = 15
                        },
                        new
                        {
                            ImagenId = 52,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/Daffodil_1P_Awareness_INT_Epic_2560x1440_2560x1440-ba126bdeac3faab0596b7c56e9c09990?h=270&resize=1&w=480",
                            JuegoId = 16
                        },
                        new
                        {
                            ImagenId = 53,
                            ImagenUrl = "https://cdn2.unrealengine.com/ttwl-gameplay-reveal-screenshots-banshee-1080-1mb-1920x1080-bf235e1791e1.jpg",
                            JuegoId = 16
                        },
                        new
                        {
                            ImagenId = 54,
                            ImagenUrl = "https://cdn2.unrealengine.com/ttwl-gameplay-reveal-screenshots-mushroom-forest-1080-1mb-1920x1080-9f8ebad39534.jpg",
                            JuegoId = 16
                        },
                        new
                        {
                            ImagenId = 55,
                            ImagenUrl = "https://cdn2.unrealengine.com/crypt-01-3840x2160-4fd5e57cdc50.jpg",
                            JuegoId = 16
                        },
                        new
                        {
                            ImagenId = 56,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/e9e3ee13329f434f94105e6ec63435e0/EGS_BioShockRemastered_MassMediaGames_S1_2560x1440-cb7067c24252c5602497ab42fc488eed?h=270&resize=1&w=480",
                            JuegoId = 17
                        },
                        new
                        {
                            ImagenId = 57,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-bioshockremastered-massmediagames-g1a-00-1920x1080-884ba4d9c648.jpg",
                            JuegoId = 17
                        },
                        new
                        {
                            ImagenId = 58,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-bioshockremastered-massmediagames-g1a-02-1920x1080-53419ae2abba.jpg",
                            JuegoId = 17
                        },
                        new
                        {
                            ImagenId = 59,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-bioshockremastered-massmediagames-g1a-04-1920x1080-ed1775dd7be6.jpg",
                            JuegoId = 17
                        },
                        new
                        {
                            ImagenId = 60,
                            ImagenUrl = "https://cdn1.epicgames.com/ark/offer/EGS_ARKSurvivalEvolved_StudioWildcard_S1-2560x1440-c316afb7c33a9dfb892eef6b99169e43.jpg?h=270&resize=1&w=480",
                            JuegoId = 18
                        },
                        new
                        {
                            ImagenId = 61,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-arksurvivalevolved-studiowildcard-g1a-07-1920x1080-136945680.jpg",
                            JuegoId = 18
                        },
                        new
                        {
                            ImagenId = 62,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-arksurvivalevolved-studiowildcard-g1a-10-1920x1080-136943551.jpg",
                            JuegoId = 18
                        },
                        new
                        {
                            ImagenId = 63,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_theHunterCalloftheWild_ExpansiveWorlds_S1_2560x1440-69120885e0b3acfb87f34ac0bad68ec6?h=270&resize=1&w=480",
                            JuegoId = 19
                        },
                        new
                        {
                            ImagenId = 64,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thehuntercallofthewild-expansiveworlds-g1a-01-1920x1080-f03607ba5431.jpg",
                            JuegoId = 19
                        },
                        new
                        {
                            ImagenId = 65,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thehuntercallofthewild-expansiveworlds-g1a-02-1920x1080-993584648afc.jpg",
                            JuegoId = 19
                        },
                        new
                        {
                            ImagenId = 66,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thehuntercallofthewild-expansiveworlds-g1a-04-1920x1080-6a94e678d7cb.jpg",
                            JuegoId = 19
                        },
                        new
                        {
                            ImagenId = 67,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/bd46d4ce259349e5bd8b3ded20274737/EGS_Chivalry2_TornBannerStudios_1_2560x1440-d9771ab1864d2db077d46f78f7731fcd?h=270&resize=1&w=480",
                            JuegoId = 20
                        },
                        new
                        {
                            ImagenId = 68,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-chivalry2-tornbannerstudios-g1a-07-1920x1080-189cecc3d888.jpg",
                            JuegoId = 20
                        },
                        new
                        {
                            ImagenId = 69,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-chivalry2-tornbannerstudios-g1a-08-1920x1080-043a3f4ff80d.jpg",
                            JuegoId = 20
                        },
                        new
                        {
                            ImagenId = 70,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-chivalry2-tornbannerstudios-g1a-09-1920x1080-53ec26c8daa3.jpg",
                            JuegoId = 20
                        },
                        new
                        {
                            ImagenId = 71,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/c315a84ec4714288b34f7ac94ee2515d/EGS_HextechMayhemALeagueofLegendsStory_ChoiceProvisions_S1_2560x1440-dfef2c02d3b783eda069dc4c636993f5?h=270&resize=1&w=480",
                            JuegoId = 21
                        },
                        new
                        {
                            ImagenId = 72,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hextechmayhemaleagueoflegendsstory-choiceprovisions-g1a-01-1920x1080-2ef9bf76c9ff.jpg",
                            JuegoId = 21
                        },
                        new
                        {
                            ImagenId = 73,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hextechmayhemaleagueoflegendsstory-choiceprovisions-g1a-02-1920x1080-e0f106febf53.jpg",
                            JuegoId = 21
                        },
                        new
                        {
                            ImagenId = 74,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-hextechmayhemaleagueoflegendsstory-choiceprovisions-g1a-03-1920x1080-ae93d4a341b9.jpg",
                            JuegoId = 21
                        },
                        new
                        {
                            ImagenId = 75,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/8ae7b3c0f490471b967ce26cc2f6e0e6/EGS_ItTakesTwo_Hazelight_S1_2560x1440-3ca0f21dd4d9ce4416e2d8e2a2178906_2560x1440-3ca0f21dd4d9ce4416e2d8e2a2178906?h=270&resize=1&w=480",
                            JuegoId = 22
                        },
                        new
                        {
                            ImagenId = 76,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-02-1920x1080-a767e6a24f42.jpg",
                            JuegoId = 22
                        },
                        new
                        {
                            ImagenId = 77,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-05-1920x1080-74e4df3b0d0b.jpg",
                            JuegoId = 22
                        },
                        new
                        {
                            ImagenId = 78,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-07-1920x1080-818d2460b157.jpg",
                            JuegoId = 22
                        },
                        new
                        {
                            ImagenId = 79,
                            ImagenUrl = "https://cdn1.epicgames.com/spt-assets/4a2dcb55ecca496aaaf328f60263bb56/kao-the-kangaroo-offer-5k0vx.jpg?h=270&resize=1&w=480",
                            JuegoId = 23
                        },
                        new
                        {
                            ImagenId = 80,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-02-1920x1080-a767e6a24f42.jpg",
                            JuegoId = 23
                        },
                        new
                        {
                            ImagenId = 81,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-05-1920x1080-74e4df3b0d0b.jpg",
                            JuegoId = 23
                        },
                        new
                        {
                            ImagenId = 82,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-ittakestwo-hazelight-g1a-07-1920x1080-818d2460b157.jpg",
                            JuegoId = 23
                        },
                        new
                        {
                            ImagenId = 83,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/75c06d52a99942e9884a47deced106bb/EGS_ELEXII_PiranhaBytes_S1_2560x1440-92c8f0e41a7628ab9eb29911f2584292?h=270&resize=1&w=480",
                            JuegoId = 24
                        },
                        new
                        {
                            ImagenId = 84,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-elexii-piranhabytes-g1a-01-1920x1080-93a49092e0e2.jpg",
                            JuegoId = 24
                        },
                        new
                        {
                            ImagenId = 85,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-elexii-piranhabytes-g1a-02-1920x1080-e4e994e861be.jpg",
                            JuegoId = 24
                        },
                        new
                        {
                            ImagenId = 86,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-elexii-piranhabytes-g1a-03-1920x1080-409cd07f0509.jpg",
                            JuegoId = 24
                        },
                        new
                        {
                            ImagenId = 87,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_THEKINGOFFIGHTERSXV_SNKCORPORATION_S1_2560x1440-5d55ab8f79aeef9e9886bac3bbbf2204?h=270&resize=1&w=480",
                            JuegoId = 25
                        },
                        new
                        {
                            ImagenId = 88,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thekingoffightersxvstandardedition-snkcorporation-bundles-g1a-01-1920x1080-a11849f0a7a3.jpg",
                            JuegoId = 25
                        },
                        new
                        {
                            ImagenId = 89,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thekingoffightersxvstandardedition-snkcorporation-bundles-g1a-02-1920x1080-00085c73794c.jpg",
                            JuegoId = 25
                        },
                        new
                        {
                            ImagenId = 90,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-thekingoffightersxvstandardedition-snkcorporation-bundles-g1a-05-1920x1080-aa58f4840b78.jpg",
                            JuegoId = 25
                        },
                        new
                        {
                            ImagenId = 91,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_TombRaiderGAMEOFTHEYEAREDITION_CrystalDynamics_S1_2560x1440-0c41fcc8db62992e8d098d304b2277f8?h=270&resize=1&w=480",
                            JuegoId = 26
                        },
                        new
                        {
                            ImagenId = 92,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tombraidergameoftheyearedition-crystaldynamics-g1a-01-1920x1080-e805b0875b06.jpg",
                            JuegoId = 26
                        },
                        new
                        {
                            ImagenId = 93,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tombraidergameoftheyearedition-crystaldynamics-g1a-04-1920x1080-f2ad3f9c089c.jpg",
                            JuegoId = 26
                        },
                        new
                        {
                            ImagenId = 94,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-tombraidergameoftheyearedition-crystaldynamics-g1a-06-1920x1080-233dd5955a75.jpg",
                            JuegoId = 26
                        },
                        new
                        {
                            ImagenId = 95,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/4b5461ca8d1c488787b5200b420de066/egs-shadowofthetombraiderdefinitiveedition-eidosmontralcrystaldynamicsnixxessoftware-s1-2560x1440-eca6506e95a1_2560x1440-193582a5fd76a593804e0171d6395cf4?h=270&resize=1&w=480",
                            JuegoId = 27
                        },
                        new
                        {
                            ImagenId = 96,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-shadowofthetombraiderdefinitiveedition-eidosmontralcrystaldynamicsnixxessoftware-g1a-01-1920x1080-508274bcd3fd.jpg",
                            JuegoId = 27
                        },
                        new
                        {
                            ImagenId = 97,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-shadowofthetombraiderdefinitiveedition-eidosmontralcrystaldynamicsnixxessoftware-g1a-02-1920x1080-54a6af8c99d1.jpg",
                            JuegoId = 27
                        },
                        new
                        {
                            ImagenId = 98,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-shadowofthetombraiderdefinitiveedition-eidosmontralcrystaldynamicsnixxessoftware-g1a-06-1920x1080-daee577d64c3.jpg",
                            JuegoId = 27
                        },
                        new
                        {
                            ImagenId = 99,
                            ImagenUrl = "https://cdn1.epicgames.com/salesEvent/salesEvent/EGS_RiseoftheTombRaider20YearCelebration_CrystalDynamics_S1_2560x1440-3bd5b3c4c11d46cc2dcb06bdf2f77627?h=270&resize=1&w=480",
                            JuegoId = 28
                        },
                        new
                        {
                            ImagenId = 100,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-riseofthetombraider20yearcelebration-crystaldynamics-g1a-02-1920x1080-f53afd374f40.jpg",
                            JuegoId = 28
                        },
                        new
                        {
                            ImagenId = 101,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-riseofthetombraider20yearcelebration-crystaldynamics-g1a-03-1920x1080-8139a7be5c54.jpg",
                            JuegoId = 28
                        },
                        new
                        {
                            ImagenId = 102,
                            ImagenUrl = "https://cdn2.unrealengine.com/egs-riseofthetombraider20yearcelebration-crystaldynamics-g1a-06-1920x1080-32ef2bd7bef9.jpg",
                            JuegoId = 28
                        },
                        new
                        {
                            ImagenId = 103,
                            ImagenUrl = "https://media.vandal.net/m/3-2022/202232312534795_1.jpg",
                            JuegoId = 29
                        },
                        new
                        {
                            ImagenId = 104,
                            ImagenUrl = "https://guiasyjuegos.com/wp-content/uploads/Kirby-y-la-tierra-olvidada-objetivo-secreto-de-Every-Winter.png",
                            JuegoId = 29
                        },
                        new
                        {
                            ImagenId = 105,
                            ImagenUrl = "https://img1.ak.crunchyroll.com/i/spire2/17460e3d58c86bcf88eb33a741a912b81632471800_main.jpg",
                            JuegoId = 29
                        },
                        new
                        {
                            ImagenId = 106,
                            ImagenUrl = "https://e00-marca.uecdn.es/assets/multimedia/imagenes/2022/01/12/16419978817192.jpg",
                            JuegoId = 29
                        },
                        new
                        {
                            ImagenId = 107,
                            ImagenUrl = "https://cdn.alfabetajuega.com/alfabetajuega/2022/06/pokemon-escarlata-purpura-koraidon-miraidon.jpg",
                            JuegoId = 30
                        },
                        new
                        {
                            ImagenId = 108,
                            ImagenUrl = "https://media.redadn.es/imagenes/pokemon-escarlata-y-pokemon-purpura-nintendo-switch_344447.jpg",
                            JuegoId = 30
                        },
                        new
                        {
                            ImagenId = 109,
                            ImagenUrl = "https://media.vandal.net/i/1200x630/6-2022/202262956397_1.jpg",
                            JuegoId = 30
                        },
                        new
                        {
                            ImagenId = 110,
                            ImagenUrl = "https://as01.epimg.net/meristation/imagenes/2022/06/01/noticias/1654093877_803563_1654094739_noticia_normal.jpg",
                            JuegoId = 30
                        },
                        new
                        {
                            ImagenId = 111,
                            ImagenUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202206/0919/hq6KtnlrPbnUj7iNNI0V6gwe.png",
                            JuegoId = 31
                        },
                        new
                        {
                            ImagenId = 112,
                            ImagenUrl = "https://www.pcmrace.com/wp-content/uploads/2021/03/ss_f6dcf0cdc756ae083c39b237a996ac070a06ce5c.1920x1080.jpg",
                            JuegoId = 31
                        },
                        new
                        {
                            ImagenId = 113,
                            ImagenUrl = "https://www.pcmrace.com/wp-content/uploads/2022/02/ss_cdf307b445e56cc26834c3c101b197722e87eb82.1920x1080.jpg",
                            JuegoId = 31
                        },
                        new
                        {
                            ImagenId = 114,
                            ImagenUrl = "https://www.fun-academy.fr/wp-content/uploads/2022/06/1655720936_Shredders-Revenge-Dev-pourrait-creer-un-contenu-telechargeable-en-fonction..jpg",
                            JuegoId = 31
                        },
                        new
                        {
                            ImagenId = 115,
                            ImagenUrl = "https://cdn.givemesport.com/wp-content/uploads/2022/05/sonic-the-hedgehog.jpg",
                            JuegoId = 1
                        },
                        new
                        {
                            ImagenId = 116,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTewjNfHf1khy__CDnR8vUbIxeb6Q9FWqbWSAhWWK62DbHTSXZWVXoFUkeb5klKmflg7jQ&usqp=CAU",
                            JuegoId = 1
                        },
                        new
                        {
                            ImagenId = 117,
                            ImagenUrl = "https://deluxe.news/wp-content/uploads/2022/04/1650468696_Sonic-Origins-Collection-to-release-in-June-with-confusing-DLC.jpg",
                            JuegoId = 1
                        },
                        new
                        {
                            ImagenId = 118,
                            ImagenUrl = "https://t2.tudocdn.net/543353?w=1920&h=1080",
                            JuegoId = 2
                        },
                        new
                        {
                            ImagenId = 119,
                            ImagenUrl = "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/4d74e8eabfe62b330b0fdc168f7b84980a72391769f19b846a095915a96a5cb0._RI_.jpg",
                            JuegoId = 2
                        },
                        new
                        {
                            ImagenId = 120,
                            ImagenUrl = "https://i.ytimg.com/vi/Tf-aqCnu4Jw/maxresdefault.jpg",
                            JuegoId = 2
                        },
                        new
                        {
                            ImagenId = 121,
                            ImagenUrl = "https://cdn1.epicgames.com/offer/03208f1f61764f5a8f6b7ea24c56edf1/XXXX_Store_Landscape_2560x1440_2560x1440-5f9186dedfc0626bcd7f347d5909723a?h=270&resize=1&w=480",
                            JuegoId = 12
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JuegoId"), 1L, 1);

                    b.Property<int>("ClasificacionId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EnOferta")
                        .HasColumnType("bit");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("JuegoId");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("Juego", (string)null);

                    b.HasData(
                        new
                        {
                            JuegoId = 1,
                            ClasificacionId = 1,
                            Descripcion = "Juegos clásicos de Sonic remasterizados.",
                            EnOferta = false,
                            NombreProducto = "Sonic Origins",
                            PlataformaId = 4,
                            Precio = 40m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/ZzHXjAJ86Zw"
                        },
                        new
                        {
                            JuegoId = 2,
                            ClasificacionId = 1,
                            Descripcion = "Juego de Crash más reciente.",
                            EnOferta = false,
                            NombreProducto = "Crash Bandicoot 4: It’s About Time",
                            PlataformaId = 2,
                            Precio = 10m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/aOGwx3Ju6QQ"
                        },
                        new
                        {
                            JuegoId = 3,
                            ClasificacionId = 3,
                            Descripcion = "Kratos ha dejado atras su venganza contra los dioses del Olimpo y vive ahora como un hombre en los dominios de los dioses y monstruos nordicos.",
                            EnOferta = false,
                            NombreProducto = "God of War",
                            PlataformaId = 1,
                            Precio = 40m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/d8HmwZSskvY"
                        },
                        new
                        {
                            JuegoId = 4,
                            ClasificacionId = 1,
                            Descripcion = "Redout es un tributo a los clásicos juegos de carreras.",
                            EnOferta = false,
                            NombreProducto = "Redout: Enhanced Edition",
                            PlataformaId = 4,
                            Precio = 4m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/kcuFK7Xadyc"
                        },
                        new
                        {
                            JuegoId = 5,
                            ClasificacionId = 1,
                            Descripcion = "Fall Guys es un party royale gratis y multiplataforma donde los jugadores compiten en delirantes carreras de obstáculos formadas por rondas cada vez más emocionantes hasta que una sola persona se alza con la victoria.",
                            EnOferta = false,
                            NombreProducto = "Fall Guys",
                            PlataformaId = 5,
                            Precio = 10m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/KNDf4J4wmxs"
                        },
                        new
                        {
                            JuegoId = 6,
                            ClasificacionId = 1,
                            Descripcion = "Crea un equipo con hasta 3 amigos en Tom Clancy's Ghost Recon® Wildlands y disfruta del shooter militar definitivo en un enorme y peligroso mundo abierto.",
                            EnOferta = false,
                            NombreProducto = "LEGO® Star Wars™: La Saga Skywalker",
                            PlataformaId = 4,
                            Precio = 50m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/watch?v=kuYiHhx1_mw"
                        },
                        new
                        {
                            JuegoId = 7,
                            ClasificacionId = 2,
                            Descripcion = "Guía a Skul en su mision para enfrentarse el solo al Ejercito Imperial y rescatar a su rey en un roguelite en 2D de plataformas cargado de accion que pasara a la historia.",
                            EnOferta = false,
                            NombreProducto = "Skul: The Hero Slayer",
                            PlataformaId = 6,
                            Precio = 4m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/7uU1mOhOTH8"
                        },
                        new
                        {
                            JuegoId = 8,
                            ClasificacionId = 1,
                            Descripcion = "Tetris® Effect: Connected amplía con una nueva y potente expansión multijugador la inmensa variedad de adictivos e innovadores modos de juego por los que se conoce a Tetris Effect.",
                            EnOferta = false,
                            NombreProducto = "Tetris® Effect: Connected",
                            PlataformaId = 6,
                            Precio = 8m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/CCBpwyS0E1o"
                        },
                        new
                        {
                            JuegoId = 9,
                            ClasificacionId = 1,
                            Descripcion = "Construye y amplía tu imperio de servicios de reparación en este juego de simulación increíblemente detallado y realista, donde la atención a los detalles de los coches es asombrosa.",
                            EnOferta = false,
                            NombreProducto = "Car Mechanic Simulator 2018",
                            PlataformaId = 5,
                            Precio = 4m,
                            SoftDelete = false,
                            Stock = 10,
                            Video = "https://www.youtube.com/embed/LCTF8wKWFSU"
                        },
                        new
                        {
                            JuegoId = 10,
                            ClasificacionId = 2,
                            Descripcion = "VALORANT es un shooter táctico 5v5 basado en personajes que está ambientado en un escenario internacional.",
                            EnOferta = false,
                            NombreProducto = "VALORANT",
                            PlataformaId = 5,
                            Precio = 0m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/KbFWhffLM-A"
                        },
                        new
                        {
                            JuegoId = 11,
                            ClasificacionId = 2,
                            Descripcion = "NARAKA: BLADEPOINT es un título de lucha y acción mítica JcJ en el que hasta 60 jugadores se enfrentan en combates cuerpo a cuerpo de artes marciales.",
                            EnOferta = false,
                            NombreProducto = "NARAKA: BLADEPOINT",
                            PlataformaId = 5,
                            Precio = 20m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/Q_uBBXiqL1s"
                        },
                        new
                        {
                            JuegoId = 12,
                            ClasificacionId = 1,
                            Descripcion = "Patina y rueda hasta la victoria en Roller Champions. Descubre un juego deportivo JcJ por equipos y gratuito unico en su especie!",
                            EnOferta = false,
                            NombreProducto = "Roller Champions",
                            PlataformaId = 3,
                            Precio = 0m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/vdKJQBf2lL0"
                        },
                        new
                        {
                            JuegoId = 13,
                            ClasificacionId = 1,
                            Descripcion = "Pon a prueba tu dominio del bláster, la espada láser y la Fuerza online y offline en STAR WARS Battlefront II: Celebration Edition.",
                            EnOferta = false,
                            NombreProducto = "STAR WARS Battlefront II",
                            PlataformaId = 4,
                            Precio = 40m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/qbVsjbBllKQ"
                        },
                        new
                        {
                            JuegoId = 14,
                            ClasificacionId = 3,
                            Descripcion = "Wolfenstein®: The New Order revitaliza la serie que creó el género de los shooters en primera persona.",
                            EnOferta = false,
                            NombreProducto = "Wolfenstein: The New Order",
                            PlataformaId = 1,
                            Precio = 13m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/nidCcGtPLOQ"
                        },
                        new
                        {
                            JuegoId = 15,
                            ClasificacionId = 3,
                            Descripcion = "Supera a las bandas rivales en un mundo medieval y violento de intensos asaltos multijugador JcJcE.",
                            EnOferta = false,
                            NombreProducto = "Hood: Outlaws & Legends",
                            PlataformaId = 1,
                            Precio = 12m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/o26rvJIBLno"
                        },
                        new
                        {
                            JuegoId = 16,
                            ClasificacionId = 2,
                            Descripcion = "¡Embárcate en una increíble aventura llena de extravagancias, asombro y armamento de alta potencia! Crea a tu propio héroe multiclase y saquea, dispara, corta y lanza hechizos para detener al Señor de los Dragones.",
                            EnOferta = false,
                            NombreProducto = "Tiny Tina's Wonderlands",
                            PlataformaId = 3,
                            Precio = 60m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/AwFCFG9aBr8"
                        },
                        new
                        {
                            JuegoId = 17,
                            ClasificacionId = 3,
                            Descripcion = "Explora la ciudad submarina de Rapture, un refugio para las mentes más brillantes de la sociedad que se ha transformado en una pesadilla distópica por culpa del orgullo desmedido de un hombre.",
                            EnOferta = false,
                            NombreProducto = "BioShock Remastered",
                            PlataformaId = 5,
                            Precio = 15m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/BeP35Jw2_ho"
                        },
                        new
                        {
                            JuegoId = 18,
                            ClasificacionId = 1,
                            Descripcion = "Despiertas en la orilla de una isla misteriosa en la que debes aprender a sobrevivir. Usa tu inteligencia para matar o domar a las criaturas primitivas que vagan por el lugar.",
                            EnOferta = false,
                            NombreProducto = "ARK: Survival Evolved",
                            PlataformaId = 4,
                            Precio = 6m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/FW9vsrPWujI"
                        },
                        new
                        {
                            JuegoId = 19,
                            ClasificacionId = 2,
                            Descripcion = "Disfruta de un juego de caza con una ambientación sin igual en un mundo abierto realista y visualmente asombroso. Sumérgete en la atmósfera de la campaña individual, o comparte la experiencia de caza definitiva con tus amigos.",
                            EnOferta = false,
                            NombreProducto = "theHunter: Call of the Wild™",
                            PlataformaId = 4,
                            Precio = 4m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/VGOTYfGMyoE"
                        },
                        new
                        {
                            JuegoId = 20,
                            ClasificacionId = 2,
                            Descripcion = "Chivalry 2 es un juego multijugador de batallas en primera persona inspiradas en las películas de estilo medieval.",
                            EnOferta = false,
                            NombreProducto = "Chivalry 2",
                            PlataformaId = 3,
                            Precio = 8m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/HKlYVpCuab0"
                        },
                        new
                        {
                            JuegoId = 21,
                            ClasificacionId = 1,
                            Descripcion = "En este trepidante juego de avance rítmico, toda acción tiene una reacción explosiva ¡y todo caos es poco! Poneos en el pelaje de Ziggs, un experto en hexplosivos, conforme desatáis el caos a través de los barrios de Piltover.",
                            EnOferta = false,
                            NombreProducto = "Hextech Mayhem",
                            PlataformaId = 6,
                            Precio = 7m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/q6eWS8OEJiE"
                        },
                        new
                        {
                            JuegoId = 22,
                            ClasificacionId = 1,
                            Descripcion = "Embárcate en la aventura de tu vida en It Takes Two. Invita a un amigo a acompañarte gratis con el Pase de amigo* para colaborar en una gran variedad de desafíos deliciosamente rompedores.",
                            EnOferta = false,
                            NombreProducto = "It Takes Two",
                            PlataformaId = 3,
                            Precio = 40m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/ohClxMmNLQQ"
                        },
                        new
                        {
                            JuegoId = 23,
                            ClasificacionId = 1,
                            Descripcion = "Vive una aventura épica, domina los guantes y explora escenarios increíbles.",
                            EnOferta = false,
                            NombreProducto = "Kao the Kangaroo",
                            PlataformaId = 4,
                            Precio = 30m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/fww1BuVIxzo"
                        },
                        new
                        {
                            JuegoId = 24,
                            ClasificacionId = 2,
                            Descripcion = "En esta secuela del RPG vintage de mundo abierto ELEX, Jax debe volver a unir a los pueblos libres del mundo de ciencia ficción y fantasía de Magalan contra una nueva amenaza, los Celestiales, que pretenden cambiar para siempre la faz del planeta.",
                            EnOferta = false,
                            NombreProducto = "ELEX II",
                            PlataformaId = 5,
                            Precio = 18m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/u49qSkdq2r8"
                        },
                        new
                        {
                            JuegoId = 25,
                            ClasificacionId = 2,
                            Descripcion = "¡REVIENTA TODAS LAS EXPECTATIVAS! ¡El nuevo XV que sobrepasa todo!",
                            EnOferta = false,
                            NombreProducto = "THE KING OF FIGHTERS XV",
                            PlataformaId = 3,
                            Precio = 29m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/9FukK1ItSZE"
                        },
                        new
                        {
                            JuegoId = 26,
                            ClasificacionId = 3,
                            Descripcion = "Armada solo con su instinto y una capacidad de aguante más allá de los límites de la resistencia humana, Lara debe luchar para huir de una isla remota y descubrir su oscura historia.",
                            EnOferta = false,
                            NombreProducto = "Tomb Raider GOTY",
                            PlataformaId = 5,
                            Precio = 20m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/OJc5yDgJ7lk"
                        },
                        new
                        {
                            JuegoId = 27,
                            ClasificacionId = 3,
                            Descripcion = "En Shadow of the Tomb Raider: Definitive Edition, vive el capítulo final de la historia sobre el origen de Lara, en el que se convierte en la saqueadora de tumbas que está destinada a ser.",
                            EnOferta = false,
                            NombreProducto = "Shadow of the Tomb Raider: Definitive Edition",
                            PlataformaId = 2,
                            Precio = 40m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/zmihOPh3enA"
                        },
                        new
                        {
                            JuegoId = 28,
                            ClasificacionId = 3,
                            Descripcion = "Rise of the Tomb Raider: Edición 20 aniversario incluye el juego de base y el pase de temporada con contenido totalmente nuevo.",
                            EnOferta = false,
                            NombreProducto = "Rise of the Tomb Raider: Edición 20 aniversario",
                            PlataformaId = 5,
                            Precio = 30m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/SfGqfEkfhjE"
                        },
                        new
                        {
                            JuegoId = 29,
                            ClasificacionId = 1,
                            Descripcion = "Kirby y la tierra olvidada, titulado en inglés como Kirby and the Forgotten Land, es un videojuego de plataformas en 3D de la saga Kirby, desarrollado por HAL Laboratory y publicado por Nintendo para la videoconsola Nintendo Switch.",
                            EnOferta = false,
                            NombreProducto = "Kirby y la tierra olvidada",
                            PlataformaId = 6,
                            Precio = 23m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/ZKNYy6IOUSE"
                        },
                        new
                        {
                            JuegoId = 30,
                            ClasificacionId = 1,
                            Descripcion = "Pokémon Escarlata y Pokémon Púrpura son un par de videojuegos de rol en desarrollo por Game Freak. Su lanzamiento está previsto para finales de 2022, ​ siendo publicados por The Pokémon Company para Nintendo Switch.",
                            EnOferta = false,
                            NombreProducto = "Pokémon escarlata y Pokémon púrpura",
                            PlataformaId = 6,
                            Precio = 17m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/yGoVJM5lpK0"
                        },
                        new
                        {
                            JuegoId = 31,
                            ClasificacionId = 1,
                            Descripcion = "Teenage Mutant Ninja Turtles: Shredder's Revenge es un juego de lucha desarrollado por Tribute Games y publicado por Dotemu.",
                            EnOferta = false,
                            NombreProducto = "Teenage Mutant Ninja Turtles: Shredder's Revenge",
                            PlataformaId = 6,
                            Precio = 27m,
                            SoftDelete = false,
                            Stock = 20,
                            Video = "https://www.youtube.com/embed/c87XkB05xtg"
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Plataforma", b =>
                {
                    b.Property<int>("PlataformaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlataformaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombrePlataforma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("PlataformaId");

                    b.ToTable("Plataforma", (string)null);

                    b.HasData(
                        new
                        {
                            PlataformaId = 1,
                            Descripcion = "Consola de Sony de última generación.",
                            NombrePlataforma = "PlayStation 5"
                        },
                        new
                        {
                            PlataformaId = 2,
                            Descripcion = "Consola de Sony de última generación.",
                            NombrePlataforma = "PlayStation 4"
                        },
                        new
                        {
                            PlataformaId = 3,
                            Descripcion = "Consola Económica de Microsoft de última generación.",
                            NombrePlataforma = "Xbox Series S"
                        },
                        new
                        {
                            PlataformaId = 4,
                            Descripcion = "Consola Económica de Microsoft de última generación.",
                            NombrePlataforma = "Xbox One"
                        },
                        new
                        {
                            PlataformaId = 5,
                            Descripcion = "Computadora de Escritorio o Notebook Gamer",
                            NombrePlataforma = "PC"
                        },
                        new
                        {
                            PlataformaId = 6,
                            Descripcion = "Consola Portatil Nintendo Switch de última generación.",
                            NombrePlataforma = "Nintendo Switch"
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.ProductoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("JuegoId");

                    b.ToTable("Producto_Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            JuegoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            JuegoId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 6,
                            JuegoId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            JuegoId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            JuegoId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            JuegoId = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 12,
                            JuegoId = 4
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 6,
                            JuegoId = 5
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 7,
                            JuegoId = 5
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 1,
                            JuegoId = 6
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 2,
                            JuegoId = 6
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 7,
                            JuegoId = 7
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            JuegoId = 7
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 3,
                            JuegoId = 8
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 6,
                            JuegoId = 8
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 11,
                            JuegoId = 9
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 12,
                            JuegoId = 9
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 1,
                            JuegoId = 10
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 4,
                            JuegoId = 10
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 10,
                            JuegoId = 10
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 1,
                            JuegoId = 11
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 2,
                            JuegoId = 11
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 9,
                            JuegoId = 11
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 12,
                            JuegoId = 12
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 1,
                            JuegoId = 13
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 2,
                            JuegoId = 13
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 1,
                            JuegoId = 14
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 4,
                            JuegoId = 14
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 1,
                            JuegoId = 15
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 2,
                            JuegoId = 15
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 3,
                            JuegoId = 15
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 9,
                            JuegoId = 15
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 2,
                            JuegoId = 16
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 4,
                            JuegoId = 16
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 9,
                            JuegoId = 16
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 10,
                            JuegoId = 16
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 1,
                            JuegoId = 17
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 4,
                            JuegoId = 17
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 10,
                            JuegoId = 17
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 1,
                            JuegoId = 18
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 2,
                            JuegoId = 18
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 8,
                            JuegoId = 18
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 9,
                            JuegoId = 18
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 10,
                            JuegoId = 18
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 2,
                            JuegoId = 19
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 9,
                            JuegoId = 19
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 10,
                            JuegoId = 19
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 11,
                            JuegoId = 19
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 1,
                            JuegoId = 20
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 10,
                            JuegoId = 20
                        },
                        new
                        {
                            Id = 51,
                            CategoriaId = 1,
                            JuegoId = 21
                        },
                        new
                        {
                            Id = 52,
                            CategoriaId = 6,
                            JuegoId = 21
                        },
                        new
                        {
                            Id = 53,
                            CategoriaId = 1,
                            JuegoId = 22
                        },
                        new
                        {
                            Id = 54,
                            CategoriaId = 2,
                            JuegoId = 22
                        },
                        new
                        {
                            Id = 55,
                            CategoriaId = 1,
                            JuegoId = 23
                        },
                        new
                        {
                            Id = 56,
                            CategoriaId = 2,
                            JuegoId = 23
                        },
                        new
                        {
                            Id = 57,
                            CategoriaId = 6,
                            JuegoId = 23
                        },
                        new
                        {
                            Id = 58,
                            CategoriaId = 1,
                            JuegoId = 24
                        },
                        new
                        {
                            Id = 59,
                            CategoriaId = 2,
                            JuegoId = 24
                        },
                        new
                        {
                            Id = 60,
                            CategoriaId = 9,
                            JuegoId = 24
                        },
                        new
                        {
                            Id = 61,
                            CategoriaId = 1,
                            JuegoId = 25
                        },
                        new
                        {
                            Id = 62,
                            CategoriaId = 7,
                            JuegoId = 25
                        },
                        new
                        {
                            Id = 63,
                            CategoriaId = 1,
                            JuegoId = 26
                        },
                        new
                        {
                            Id = 64,
                            CategoriaId = 2,
                            JuegoId = 26
                        },
                        new
                        {
                            Id = 65,
                            CategoriaId = 9,
                            JuegoId = 26
                        },
                        new
                        {
                            Id = 66,
                            CategoriaId = 1,
                            JuegoId = 27
                        },
                        new
                        {
                            Id = 67,
                            CategoriaId = 2,
                            JuegoId = 27
                        },
                        new
                        {
                            Id = 68,
                            CategoriaId = 9,
                            JuegoId = 27
                        },
                        new
                        {
                            Id = 69,
                            CategoriaId = 1,
                            JuegoId = 28
                        },
                        new
                        {
                            Id = 70,
                            CategoriaId = 2,
                            JuegoId = 28
                        },
                        new
                        {
                            Id = 71,
                            CategoriaId = 9,
                            JuegoId = 28
                        },
                        new
                        {
                            Id = 72,
                            CategoriaId = 1,
                            JuegoId = 29
                        },
                        new
                        {
                            Id = 73,
                            CategoriaId = 2,
                            JuegoId = 29
                        },
                        new
                        {
                            Id = 74,
                            CategoriaId = 7,
                            JuegoId = 29
                        },
                        new
                        {
                            Id = 75,
                            CategoriaId = 9,
                            JuegoId = 29
                        },
                        new
                        {
                            Id = 76,
                            CategoriaId = 1,
                            JuegoId = 30
                        },
                        new
                        {
                            Id = 77,
                            CategoriaId = 2,
                            JuegoId = 30
                        },
                        new
                        {
                            Id = 78,
                            CategoriaId = 7,
                            JuegoId = 30
                        },
                        new
                        {
                            Id = 79,
                            CategoriaId = 9,
                            JuegoId = 30
                        },
                        new
                        {
                            Id = 80,
                            CategoriaId = 1,
                            JuegoId = 31
                        },
                        new
                        {
                            Id = 81,
                            CategoriaId = 2,
                            JuegoId = 31
                        },
                        new
                        {
                            Id = 82,
                            CategoriaId = 7,
                            JuegoId = 31
                        },
                        new
                        {
                            Id = 83,
                            CategoriaId = 1,
                            JuegoId = 16
                        });
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Imagen", b =>
                {
                    b.HasOne("TopEntertainment.Juegos.Domain.Entities.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .IsRequired();

                    b.Navigation("Juego");
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Juego", b =>
                {
                    b.HasOne("TopEntertainment.Juegos.Domain.Entities.Clasificacion", "Clasificacion")
                        .WithMany("Juegos")
                        .HasForeignKey("ClasificacionId")
                        .IsRequired();

                    b.HasOne("TopEntertainment.Juegos.Domain.Entities.Plataforma", "Plataforma")
                        .WithMany("Juegos")
                        .HasForeignKey("PlataformaId")
                        .IsRequired();

                    b.Navigation("Clasificacion");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.ProductoCategoria", b =>
                {
                    b.HasOne("TopEntertainment.Juegos.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .IsRequired();

                    b.HasOne("TopEntertainment.Juegos.Domain.Entities.Juego", "Juego")
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Juego");
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Clasificacion", b =>
                {
                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("TopEntertainment.Juegos.Domain.Entities.Plataforma", b =>
                {
                    b.Navigation("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
